apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elixir-plug-poc
  labels:
    app: elixir-plug-poc
  namespace: default
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: elixir-plug-poc
  serviceName: "elixir-plug-poc"
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: elixir-plug-poc
    spec:
      containers:
      - args:
        - foreground
        image: binarytemple/elixir_plug_poc
        imagePullPolicy: Always
        name: elixir-plug-poc
        ports:
        - containerPort: 4000
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
