kind: PersistentVolume
apiVersion: v1
metadata:
  name: data 
  labels:
    app: elasticsearch
spec:
  capacity:
    storage: 2Gi
  hostPath:
    path: /data
    type: ''
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
